appType: HTTP #"HTTP", "gRPC", "Task", "Kafka"
logLevel: 1   #日志记录登记
logFile: "mylogfile.log"  #日志文件地址  可以选择  logs/a.log  最前面不要带 “/”  并且请确保文件夹存在
servies_name: test   #服务名称


micro : # 微服务相关配置  （非必须）
  is_reg : true  #是否有服务注册
  is_heart_push : true  #是否心跳推送
  is_remove_service : true  #退出推送
  heart_push_speed : 5  #心跳推送速度 单位 秒  如果不填写将只执行1次 ，默认用户方法内部处理心跳逻辑

databases:
  - name: test
    host: 127.0.0.1
    port: 3306
    username: root
    password: root
    dbname: test
    maxIdleConns: 10
    maxOpenConns: 10
    type : "mysql"  #数据库类型mysql pgsql

redis:
  - name: test
    host : 127.0.0.1
    port : 6379
    password:
    db : 0
    poolSize: 10

kafkaProducers:
  - name: Producer1
    brokers: ["broker1:9092", "broker2:9092"] # Kafka集群的地址列表
    topic: test # 默认的主题
    compression: gzip # 消息压缩方式，可选的值包括"gzip"、"snappy"、"lz4"、"zstd"、"none"
    timeout: 5000 # 发送消息的超时时间，单位为毫秒
    batchSize: 500 # 批量发送的消息数量，超过这个数量后就发送
    batchTime: 5000  # 批量发送的时间间隔，超过这个时间就发送，单位为毫秒
    waitForAll: true  # 是否等待服务器所有副本都保存成功后再返回
    maxRetries: 3 # 重试的最大次数
    retryBackoff: 100  # 两次重试之间的时间间隔，单位为毫秒
    returnSuccesses: false   # 是否返回成功发送的消息
    newManualPartitioner: false  #是否手动分配分区

es:
  - name: "es1"
    hosts: ["http://127.0.0.1:9200"] # ES集群的地址列表  携带协议 http|https://host:port
    user: ""
    pass: ""
    cloudid: "cloudId"
    apiKey: "apiKey"
    type: "host"  # 类型默认 host  使用用户名密码登录  cloud 使用 cloudid+apiKey 登录
    version: "v8" #v8 v7  根据 es 版本填写

mongoConfig :
  - name: "es1"
    host: "127.0.0.1"  # ES集群的地址列表
    port: "9200"  # ES集群的地址列表
    username: ""
    password: ""
    dbname: "dbname"



httpginServer:
  port: 8080  #服务端口
  appendPprof : true #是否在路由中添加 pprof 路由
  iPConcurrencyLimit: 5 #单ip 最大并发数控制  0 为不限制 ，将不处理ip并发问题

grpcServer:
  port: 8080  #服务端口



kafkaConsumers:
  - name: "Consumer1"
    brokers: ["broker1:9092", "broker2:9092"]
    topics: ["my-topic-1", "my-topic-2"]
    groupID: "my-group-1"
    autoOffsetReset: "earliest"  # 开始消费的位置，可能的值包括'earliest'、'latest'、'none'
    maxWaitTime: 500  # 从Kafka获取记录的最大等待时间（毫秒）
    sessionTimeout: 10000  # 消费者组会话的超时时间（毫秒）
    heartbeatInterval: 3000  # 心跳间隔时间（毫秒）


linkTracking:
  is_open: true  #是否开启链路追踪
  kafka_producer_name: linkTrackingKafka #对应推送 kafka 地址

