appType: Kafka #"HTTP", "gRPC", "Task", "Kafka"
logLevel: 3
logFile: "mylogfile.log"
servies_name: test


kafkaConsumers:
  - name: "ab_test"
    brokers: ["127.0.0.1:9092"]
    topics: ["auto_LinkTracking"]
    groupID: auto_LinkTracking
    autoOffsetReset: none  # 开始消费的位置，可能的值包括'earliest'、'latest'、'none'
    maxWaitTime: 3000  # 从Kafka获取记录的最大等待时间（毫秒）
    sessionTimeout: 6000  # 消费者组会话的超时时间（毫秒）
    heartbeatInterval: 300  # 心跳间隔时间（毫秒）
    


kafkaProducers:
  - name: linkTrackingKafka
    brokers: ["127.0.0.1:9092"] # Kafka集群的地址列表
    topic: auto_LinkTracking # 默认的主题
    compression: gzip # 消息压缩方式，可选的值包括"gzip"、"snappy"、"lz4"、"zstd"、"none"
    timeout: 5000 # 发送消息的超时时间，单位为毫秒
    batchSize: 1 # 批量发送的消息数量，超过这个数量后就发送
    batchTime: 10  # 批量发送的时间间隔，超过这个时间就发送，单位为毫秒
    waitForAll: true  # 是否等待服务器所有副本都保存成功后再返回
    maxRetries: 3 # 重试的最大次数
    retryBackoff: 100  # 两次重试之间的时间间隔，单位为毫秒
    returnSuccesses: true   # 是否返回成功发送的消息
    newManualPartitioner: false  #是否手动分配分区


linkTracking:
  is_open: true  #是否开启链路追踪
  kafka_producer_name: linkTrackingKafka #对应推送 kafka 地址