appType: Kafka #"HTTP", "gRPC", "Task", "Kafka"
logLevel: 3
logFile: "mylogfile.log"
servies_name: test

databases:
  - name: test
    host: 127.0.0.1
    port: 3306
    username: root
    password: root
    dbname: test
    maxIdleConns: 10
    MaxOpenConns: 10
redis:
  - name: test
    host : 127.0.0.1
    port : 6379
    password:
    db : 0
    poolSize: 10


httpgin:
  port: 8080  #服务端口
  appendPprof: true #是否在路由中添加 pprof 路由


kafkaConsumers:
  - name: "Consumer1"
    brokers: ["broker1:9092", "broker2:9092"]
    topics: ["my-topic-1", "my-topic-2"]
    groupID: "my-group-1"
    autoOffsetReset: "earliest"  # 开始消费的位置，可能的值包括'earliest'、'latest'、'none'
    maxWaitTime: 500  # 从Kafka获取记录的最大等待时间（毫秒）
    sessionTimeout: 10000  # 消费者组会话的超时时间（毫秒）
    heartbeatInterval: 3000  # 心跳间隔时间（毫秒）
    
  - name: "Consumer2"
    brokers: ["broker3:9092", "broker4:9092"]
    topics: ["my-topic-3"]
    groupID: "my-group-2"
    autoOffsetReset: "earliest"  # 开始消费的位置，可能的值包括'earliest'、'latest'、'none'
    maxWaitTime: 500  # 从Kafka获取记录的最大等待时间（毫秒）
    sessionTimeout: 10000  # 消费者组会话的超时时间（毫秒）
    heartbeatInterval: 3000  # 心跳间隔时间（毫秒）

